export const PRIVILEGED_SCRIPT = [
    'set -eu',
    'operation=$1',
    'plymouth_image=$3',
    'hide_firmware_logo=$4',
    'firmware_logo=$5',
    'source_image=${2-}',
    'target_image=/usr/share/backgrounds/login-background.jpg',
    'config_file=/usr/share/gdm/dconf/90-login-background',
    'config_tmp=/usr/share/gdm/dconf/.90-login-background.tmp',
    'lock_file=/usr/share/gdm/dconf/locks/90-login-background',
    'lock_tmp=/usr/share/gdm/dconf/locks/.90-login-background.tmp',
    'plymouth_theme_dir=/usr/share/plymouth/themes/login-background',
    'plymouth_theme_file=$plymouth_theme_dir/login-background.plymouth',
    'plymouth_theme_tmp=$plymouth_theme_dir/.login-background.plymouth.tmp',
    'plymouth_state_dir=/var/lib/login-background',
    'plymouth_original_file=$plymouth_state_dir/plymouth-original-theme',
    'case "$hide_firmware_logo" in 0|1) ;; *) echo "厂商 Logo 开关参数无效" >&2; exit 2 ;; esac',
    'trap \'/usr/bin/rm -f -- "$config_tmp" "$lock_tmp" "$plymouth_theme_tmp"\' EXIT',
    'set_plymouth() {',
    '    [ -x /usr/sbin/update-initramfs ] || { echo "系统缺少 update-initramfs" >&2; exit 1; }',
    '    [ -d /usr/share/plymouth/themes/spinner ] || { echo "系统缺少 Plymouth spinner 主题" >&2; exit 1; }',
    '    [ -f "$plymouth_image" ] || { echo "Plymouth 背景图片不存在" >&2; exit 1; }',
    '    [ "$(/usr/bin/file -b --mime-type -- "$plymouth_image")" = image/png ] || { echo "Plymouth 背景必须是 PNG" >&2; exit 1; }',
    '    plymouth_size=$(/usr/bin/stat -Lc %s -- "$plymouth_image")',
    '    [ "$plymouth_size" -le 52428800 ] || { echo "Plymouth 背景超过 50 MiB" >&2; exit 1; }',
    '    /usr/bin/install -d -m 0755 "$plymouth_theme_dir" "$plymouth_state_dir"',
    '    if [ ! -f "$plymouth_original_file" ]; then',
    '        original_theme=$(/usr/bin/readlink -f /etc/alternatives/default.plymouth)',
    '        [ -f "$original_theme" ] || { echo "无法确定原 Plymouth 主题" >&2; exit 1; }',
    '        original_mode=$(/usr/bin/update-alternatives --query default.plymouth | /usr/bin/sed -n "s/^Status: //p")',
    '        case "$original_mode" in auto|manual) ;; *) echo "无法确定 Plymouth 主题模式" >&2; exit 1 ;; esac',
    '        /usr/bin/printf "%s\n%s\n" "$original_theme" "$original_mode" > "$plymouth_original_file"',
    '        /usr/bin/chmod 0644 "$plymouth_original_file"',
    '    fi',
    '    /usr/bin/cp -a /usr/share/plymouth/themes/spinner/. "$plymouth_theme_dir/"',
    '    if [ "$hide_firmware_logo" = 0 ] && [ -n "$firmware_logo" ]; then',
    '        [ -f "$firmware_logo" ] || { echo "厂商 Logo 图片不存在" >&2; exit 1; }',
    '        [ "$(/usr/bin/file -b --mime-type -- "$firmware_logo")" = image/png ] || { echo "厂商 Logo 必须是 PNG" >&2; exit 1; }',
    '        /usr/bin/install -m 0644 -- "$firmware_logo" "$plymouth_theme_dir/watermark.png"',
    '    else',
    '        /usr/bin/rm -f -- "$plymouth_theme_dir/watermark.png"',
    '    fi',
    '    /usr/bin/install -m 0644 -- "$plymouth_image" "$plymouth_theme_dir/background.png"',
    "    /usr/bin/printf '%s\n' \\",
    "        '[Plymouth Theme]' \\",
    "        'Name=Ubuntu Appearance' \\",
    "        'Description=Ubuntu boot wallpaper managed by Ubuntu Appearance' \\",
    "        'ModuleName=two-step' \\",
    "        '' \\",
    "        '[two-step]' \\",
    "        'Font=Ubuntu 12' \\",
    "        'TitleFont=Ubuntu Light 30' \\",
    "        'ImageDir=/usr/share/plymouth/themes/login-background' \\",
    "        'HorizontalAlignment=.5' \\",
    "        'VerticalAlignment=.7' \\",
    "        'WatermarkHorizontalAlignment=.5' \\",
    "        'WatermarkVerticalAlignment=.5' \\",
    "        'Transition=none' \\",
    "        'TransitionDuration=0.0' \\",
    "        'BackgroundStartColor=0x000000' \\",
    "        'BackgroundEndColor=0x000000' \\",
    "        'ProgressBarBackgroundColor=0x606060' \\",
    "        'ProgressBarForegroundColor=0xffffff' \\",
    "        'ScaleBackgroundImage=true' \\",
    "        'DialogClearsFirmwareBackground=true' \\",
    "        'MessageBelowAnimation=true' \\",
    "        '' \\",
    "        '[boot-up]' \\",
    "        'UseEndAnimation=false' \\",
    "        'UseFirmwareBackground=false' \\",
    "        '' \\",
    "        '[shutdown]' \\",
    "        'UseEndAnimation=false' \\",
    "        'UseFirmwareBackground=false' \\",
    "        '' \\",
    "        '[reboot]' \\",
    "        'UseEndAnimation=false' \\",
    "        'UseFirmwareBackground=false' > \"$plymouth_theme_tmp\"",
    '    /usr/bin/chmod 0644 "$plymouth_theme_tmp"',
    '    /usr/bin/mv -f -- "$plymouth_theme_tmp" "$plymouth_theme_file"',
    '    /usr/bin/update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth "$plymouth_theme_file" 200',
    '    /usr/bin/update-alternatives --set default.plymouth "$plymouth_theme_file"',
    '    /usr/sbin/update-initramfs -u',
    '}',
    'set_firmware_logo() {',
    '    [ -f "$plymouth_theme_file" ] || { echo "请先设置开关机画面" >&2; exit 1; }',
    '    if [ "$hide_firmware_logo" = 1 ]; then',
    '        /usr/bin/rm -f -- "$plymouth_theme_dir/watermark.png"',
    '    else',
    '        [ -f "$firmware_logo" ] || { echo "厂商 Logo 图片不存在" >&2; exit 1; }',
    '        [ "$(/usr/bin/file -b --mime-type -- "$firmware_logo")" = image/png ] || { echo "厂商 Logo 必须是 PNG" >&2; exit 1; }',
    '        /usr/bin/install -m 0644 -- "$firmware_logo" "$plymouth_theme_dir/watermark.png"',
    '    fi',
    '    /usr/sbin/update-initramfs -u',
    '}',
    'restore_plymouth() {',
    '    [ -f "$plymouth_original_file" ] || return 0',
    '    original_theme=$(/usr/bin/sed -n "1p" "$plymouth_original_file")',
    '    original_mode=$(/usr/bin/sed -n "2p" "$plymouth_original_file")',
    '    case "$original_theme" in /usr/share/plymouth/themes/*/*.plymouth) ;; *) echo "保存的 Plymouth 主题路径无效" >&2; exit 1 ;; esac',
    '    case "$original_mode" in auto|manual) ;; *) echo "保存的 Plymouth 主题模式无效" >&2; exit 1 ;; esac',
    '    [ -f "$original_theme" ] || { echo "原 Plymouth 主题不存在" >&2; exit 1; }',
    '    /usr/bin/update-alternatives --set default.plymouth "$original_theme"',
    '    /usr/bin/update-alternatives --remove default.plymouth "$plymouth_theme_file"',
    '    [ "$original_mode" = manual ] || /usr/bin/update-alternatives --auto default.plymouth',
    '    /usr/bin/rm -rf -- "$plymouth_theme_dir"',
    '    /usr/bin/rm -f -- "$plymouth_original_file"',
    '    /usr/bin/rmdir "$plymouth_state_dir" 2>/dev/null || true',
    '    /usr/sbin/update-initramfs -u',
    '}',
    'case "$operation" in',
    '    set-login)',
    '        [ -f "$source_image" ] || { echo "图片不存在或不是普通文件" >&2; exit 1; }',
    '        case "$source_image" in',
    '            *.[jJ][pP][gG]|*.[jJ][pP][eE][gG]|*.[pP][nN][gG]|*.[wW][eE][bB][pP]) ;;',
    '            *) echo "只支持 JPG、PNG 和 WEBP 图片" >&2; exit 1 ;;',
    '        esac',
    '        image_size=$(/usr/bin/stat -Lc %s -- "$source_image")',
    '        [ "$image_size" -le 104857600 ] || { echo "图片超过 100 MiB" >&2; exit 1; }',
    '        /usr/bin/install -m 0644 -- "$source_image" "$target_image"',
    "        /usr/bin/printf '%s\\n' \\",
    "            '[com/ubuntu/login-screen]' \\",
    "            \"background-picture-uri='file:///usr/share/backgrounds/login-background.jpg'\" \\",
    "            \"background-size='cover'\" \\",
    "            \"background-repeat='no-repeat'\" \\",
    "            '' \\",
    "            '[org/gnome/login-screen]' \\",
    "            \"logo=''\" \\",
    "            \"fallback-logo=''\" > \"$config_tmp\"",
    "        /usr/bin/printf '%s\\n' \\",
    "            '/com/ubuntu/login-screen/background-picture-uri' \\",
    "            '/com/ubuntu/login-screen/background-size' \\",
    "            '/com/ubuntu/login-screen/background-repeat' \\",
    "            '/org/gnome/login-screen/logo' \\",
    "            '/org/gnome/login-screen/fallback-logo' > \"$lock_tmp\"",
    '        /usr/bin/chmod 0644 "$config_tmp"',
    '        /usr/bin/chmod 0644 "$lock_tmp"',
    '        /usr/bin/mv -f -- "$config_tmp" "$config_file"',
    '        /usr/bin/mv -f -- "$lock_tmp" "$lock_file"',
    '        /usr/share/gdm/generate-config',
    '        ;;',
    '    clear-login)',
    '        /usr/bin/rm -f -- "$config_file" "$lock_file"',
    '        /usr/bin/rm -f -- "$target_image"',
    '        /usr/share/gdm/generate-config',
    '        ;;',
    '    set-plymouth) set_plymouth ;;',
    '    clear-plymouth) restore_plymouth ;;',
    '    set-firmware-logo) set_firmware_logo ;;',
    '    *) echo "未知操作" >&2; exit 2 ;;',
    'esac',
].join('\n');
